const quizData = {
  easy: [
    {
      question:
        "Từ khóa nào dùng để khai báo một biến không thể thay đổi giá trị?",
      ansA: "var",
      ansB: "let",
      ansC: "const",
      ansD: "static",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Cách nào để viết ghi chú (comment) trên một dòng trong JS?",
      ansA: "",
      ansB: "//",
      ansC: "/* */",
      ansD: "??",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Hàm nào dùng để hiển thị hộp thoại thông báo?",
      ansA: "msg()",
      ansB: "print()",
      ansC: "alert()",
      ansD: "log()",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Ký hiệu nào dùng để so sánh bằng cả giá trị và kiểu dữ liệu?",
      ansA: "==",
      ansB: "=",
      ansC: "===",
      ansD: "!=",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Đâu là kiểu dữ liệu cơ bản (primitive) trong JS?",
      ansA: "Object",
      ansB: "String",
      ansC: "Array",
      ansD: "Function",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Lệnh console.log(typeof []) sẽ trả về kết quả gì?",
      ansA: "array",
      ansB: "list",
      ansC: "object",
      ansD: "undefined",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Để lấy độ dài của mảng 'arr', ta dùng thuộc tính nào?",
      ansA: "arr.size",
      ansB: "arr.length",
      ansC: "arr.count",
      ansD: "arr.index",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Phương thức nào dùng để thêm phần tử vào cuối mảng?",
      ansA: "push()",
      ansB: "pop()",
      ansC: "shift()",
      ansD: "unshift()",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Sự kiện nào xảy ra khi người dùng click vào phần tử HTML?",
      ansA: "onchange",
      ansB: "onmouseclick",
      ansC: "onclick",
      ansD: "onhover",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Lệnh 'for' thường dùng để làm gì?",
      ansA: "Khai báo biến",
      ansB: "Vòng lặp",
      ansC: "Điều kiện",
      ansD: "Tính toán",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "NaN có nghĩa là gì?",
      ansA: "Not a Number",
      ansB: "Null and None",
      ansC: "New and Next",
      ansD: "Negative a Number",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "JS chạy ở đâu là phổ biến nhất?",
      ansA: "Server-side",
      ansB: "Trình duyệt web",
      ansC: "Cơ sở dữ liệu",
      ansD: "Hệ điều hành",
      rightAns: "b",
      category: "JS",
    },
    {
      question:
        "Dấu để kết thúc một câu lệnh trong JS (không bắt buộc nhưng nên dùng)?",
      ansA: ":",
      ansB: ",",
      ansC: ".",
      ansD: ";",
      rightAns: "d",
      category: "JS",
    },
    {
      question: "Lệnh if (x != 5) có nghĩa là gì?",
      ansA: "Nếu x bằng 5",
      ansB: "Nếu x khác 5",
      ansC: "Nếu x lớn hơn 5",
      ansD: "Nếu x nhỏ hơn 5",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Làm thế nào để viết một hàm trong JS?",
      ansA: "function:myFunc()",
      ansB: "function = myFunc()",
      ansC: "function myFunc()",
      ansD: "new function myFunc()",
      rightAns: "c",
      category: "JS",
    },
  ],
  medium: [
    {
      question: "Kết quả của '5' + 2 là gì?",
      ansA: "7",
      ansB: "52",
      ansC: "NaN",
      ansD: "undefined",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Phương thức nào dùng để gộp các phần tử mảng thành một chuỗi?",
      ansA: "join()",
      ansB: "concat()",
      ansC: "slice()",
      ansD: "split()",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Sự khác biệt chính giữa 'let' và 'var' là gì?",
      ansA: "Tốc độ thực thi",
      ansB: "Phạm vi (Scope)",
      ansC: "Kiểu dữ liệu",
      ansD: "Không có sự khác biệt",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Kết quả của [ ] == ! [ ] là gì?",
      ansA: "true",
      ansB: "false",
      ansC: "undefined",
      ansD: "TypeError",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Hàm 'map()' trong mảng dùng để làm gì?",
      ansA: "Lọc phần tử",
      ansB: "Sắp xếp mảng",
      ansC: "Tạo mảng mới từ mảng cũ",
      ansD: "Xóa mảng",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Toán tử '??' gọi là gì?",
      ansA: "Ternary operator",
      ansB: "Nullish coalescing",
      ansC: "Logical OR",
      ansD: "Bitwise operator",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Làm sao để chuyển một chuỗi JSON thành Object JS?",
      ansA: "JSON.parse()",
      ansB: "JSON.stringify()",
      ansC: "JSON.convert()",
      ansD: "JSON.toObject()",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Từ khóa 'this' trong một phương thức của object trỏ về đâu?",
      ansA: "Global object",
      ansB: "Chính object đó",
      ansC: "Function cha",
      ansD: "undefined",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Phương thức nào xóa phần tử cuối cùng của mảng?",
      ansA: "shift()",
      ansB: "splice()",
      ansC: "pop()",
      ansD: "slice()",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Biểu thức 10 / '2' trả về kết quả nào?",
      ansA: "5",
      ansB: "'5'",
      ansC: "NaN",
      ansD: "Error",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Mục đích của 'use strict' là gì?",
      ansA: "Chạy code nhanh hơn",
      ansB: "Bắt lỗi bảo mật",
      ansC: "Bắt buộc viết code nghiêm ngặt hơn",
      ansD: "Để dùng ES6",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Làm thế nào để kiểm tra một biến có phải là Array không?",
      ansA: "typeof variable === 'array'",
      ansB: "variable instanceof Array",
      ansC: "Array.isArray(variable)",
      ansD: "Cả B và C",
      rightAns: "d",
      category: "JS",
    },
    {
      question: "setTimeout(fn, 0) sẽ chạy khi nào?",
      ansA: "Ngay lập tức",
      ansB: "Sau khi hàng đợi sự kiện trống",
      ansC: "Sau 1 giây",
      ansD: "Không bao giờ chạy",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Kết quả của Boolean('false') là gì?",
      ansA: "true",
      ansB: "false",
      ansC: "NaN",
      ansD: "null",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Lệnh nào dừng vòng lặp ngay lập tức?",
      ansA: "stop",
      ansB: "exit",
      ansC: "break",
      ansD: "continue",
      rightAns: "c",
      category: "JS",
    },
  ],
  hard: [
    {
      question: "Closure trong JS là gì?",
      ansA: "Một hàm đóng gói dữ liệu",
      ansB: "Hàm có quyền truy cập phạm vi của hàm cha ngay cả khi hàm cha đã đóng",
      ansC: "Cách để xóa biến khỏi bộ nhớ",
      ansD: "Một dạng vòng lặp vô hạn",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Kết quả của 0.1 + 0.2 === 0.3 là gì?",
      ansA: "true",
      ansB: "false",
      ansC: "undefined",
      ansD: "NaN",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Sự khác biệt giữa Arrow Function và Regular Function là gì?",
      ansA: "Cú pháp viết",
      ansB: "Cách xử lý từ khóa 'this'",
      ansC: "Khả năng dùng làm Constructor",
      ansD: "Cả A, B và C",
      rightAns: "d",
      category: "JS",
    },
    {
      question: "Hoisting trong JS là gì?",
      ansA: "Đưa khai báo biến/hàm lên đầu phạm vi",
      ansB: "Tối ưu hóa bộ nhớ",
      ansC: "Xóa bỏ các biến thừa",
      ansD: "Một kỹ thuật render ảnh",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Phương thức 'bind()' dùng để làm gì?",
      ansA: "Gộp hai mảng",
      ansB: "Tạo hàm mới với 'this' được chỉ định",
      ansC: "Lặp qua các thuộc tính object",
      ansD: "Đóng kết nối database",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Promise có mấy trạng thái cơ bản?",
      ansA: "2",
      ansB: "3",
      ansC: "4",
      ansD: "5",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Temporal Dead Zone (TDZ) liên quan đến từ khóa nào?",
      ansA: "var",
      ansB: "function",
      ansC: "let/const",
      ansD: "import",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Kỹ thuật 'Currying' trong JS là gì?",
      ansA: "Chuyển hàm nhiều tham số thành chuỗi các hàm 1 tham số",
      ansB: "Gộp các file JS lại",
      ansC: "Sử dụng đệ quy",
      ansD: "Thay đổi giá trị hằng số",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Event Bubbling là gì?",
      ansA: "Sự kiện lan truyền từ cha xuống con",
      ansB: "Sự kiện lan truyền từ con lên các tổ tiên",
      ansC: "Sự kiện bị hủy bỏ",
      ansD: "Sự kiện lặp vô hạn",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Để ngăn chặn kế thừa của một Class, ta dùng?",
      ansA: "final",
      ansB: "static",
      ansC: "JS không hỗ trợ trực tiếp việc này",
      ansD: "private",
      rightAns: "c",
      category: "JS",
    },
    {
      question: "Kết quả của typeof typeof 1 là gì?",
      ansA: "number",
      ansB: "string",
      ansC: "object",
      ansD: "undefined",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "WeakMap khác Map ở điểm nào chính yếu?",
      ansA: "Tốc độ nhanh hơn",
      ansB: "Chỉ nhận Object làm key và hỗ trợ Garbage Collection",
      ansC: "Dễ sử dụng hơn",
      ansD: "Không có sự khác biệt",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Phương thức Object.freeze() làm gì?",
      ansA: "Xóa object",
      ansB: "Ngăn thay đổi thuộc tính hiện có và thêm mới",
      ansC: "Ẩn object",
      ansD: "Tăng tốc độ truy cập",
      rightAns: "b",
      category: "JS",
    },
    {
      question: "Toán tử 'spread' (...) dùng để làm gì?",
      ansA: "Sao chép mảng/object",
      ansB: "Tính tổng",
      ansC: "So sánh",
      ansD: "Khai báo hàm",
      rightAns: "a",
      category: "JS",
    },
    {
      question: "Async/Await thực chất được xây dựng dựa trên?",
      ansA: "Generator & Promise",
      ansB: "XHR",
      ansC: "For loop",
      ansD: "If/Else",
      rightAns: "a",
      category: "JS",
    },
  ],
};

export default quizData;